-- MySQL Script generated by MySQL Workbench
-- Wed Nov  8 19:15:40 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema shareit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shareit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shareit` DEFAULT CHARACTER SET utf8 ;
USE `shareit` ;

-- -----------------------------------------------------
-- Table `shareit`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shareit`.`book` (
  `book_id` INT(11) NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(45) NOT NULL,
  `title` VARCHAR(1000) NOT NULL,
  `description` VARCHAR(5000) NULL DEFAULT NULL,
  `sub_description` VARCHAR(1000) NULL DEFAULT NULL,
  `author` VARCHAR(1000) NULL DEFAULT NULL,
  `company` VARCHAR(1000) NULL DEFAULT NULL,
  `image` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`book_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shareit`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shareit`.`user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `address` VARCHAR(1000) NULL DEFAULT NULL,
  `lat` FLOAT NULL DEFAULT NULL,
  `lon` FLOAT NULL DEFAULT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `role` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`, `username`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shareit`.`bookcase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shareit`.`bookcase` (
  `bookcase_id` INT(11) NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT(11) NOT NULL,
  `book_id` INT(11) NOT NULL,
  PRIMARY KEY (`bookcase_id`),
  INDEX `fk_bookcase_book_idx` (`book_id` ASC),
  INDEX `fk_bookcase_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_bookcase_book`
    FOREIGN KEY (`book_id`)
    REFERENCES `shareit`.`book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookcase_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `shareit`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shareit`.`borrow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shareit`.`borrow` (
  `borrow_id` INT(11) NOT NULL AUTO_INCREMENT,
  `borrow_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `return_date` TIMESTAMP NULL DEFAULT NULL,
  `status` VARCHAR(15) NULL DEFAULT NULL,
  `user_id_borrow` INT(11) NOT NULL,
  `bookcase_id` INT(11) NOT NULL,
  PRIMARY KEY (`borrow_id`),
  INDEX `fk_borrow_user_idx` (`user_id_borrow` ASC),
  INDEX `fk_borrow_bookcase_idx` (`bookcase_id` ASC),
  CONSTRAINT `fk_borrow_bookcase`
    FOREIGN KEY (`bookcase_id`)
    REFERENCES `shareit`.`bookcase` (`bookcase_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_borrow_user`
    FOREIGN KEY (`user_id_borrow`)
    REFERENCES `shareit`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shareit`.`rate_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shareit`.`rate_book` (
  `rate_id` INT(11) NOT NULL AUTO_INCREMENT,
  `review` VARCHAR(1000) NULL DEFAULT NULL,
  `star` INT(11) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT(11) NOT NULL,
  `book_id` INT(11) NOT NULL,
  PRIMARY KEY (`rate_id`),
  INDEX `fk_rate_book_book_idx` (`book_id` ASC),
  INDEX `fk_rate_book_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_rate_book_book`
    FOREIGN KEY (`book_id`)
    REFERENCES `shareit`.`book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rate_book_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `shareit`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shareit`.`rate_bookcase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shareit`.`rate_bookcase` (
  `rate_bookcase_id` INT(11) NOT NULL AUTO_INCREMENT,
  `review` VARCHAR(1000) NULL DEFAULT NULL,
  `star` INT(11) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT(11) NOT NULL,
  `bookcase_id` INT(11) NOT NULL,
  PRIMARY KEY (`rate_bookcase_id`),
  INDEX `fk_rate_bookcase_user_idx` (`user_id` ASC),
  INDEX `fk_rate_bookcase_bookcase_idx` (`bookcase_id` ASC),
  CONSTRAINT `fk_rate_bookcase_bookcase`
    FOREIGN KEY (`bookcase_id`)
    REFERENCES `shareit`.`bookcase` (`bookcase_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rate_bookcase_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `shareit`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
